modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "modtemplate"
displayName = "Mod Template"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "A Mod Author"
description = '''A Mod Description'''

[[mixins]]
config = "modtemplate.mixins.json"

[[dependencies.modtemplate]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modtemplate]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"